### ISSUE TITLE
Question: How could we render html content to the docx template

### ISSUE THREAD

**Issue by datcv** [alonrbar/easy-template-x#105] opened 2024-02-15 10:56 UTC
I have html content which includes html tags such as table, b, img, h1, h2, h3... I want to render this in the docx template.

I've found there is an extension for this purpose https://github.com/cvaize/easy-template-x-extension-html/ but it is NOT working.
Wonder if anyone has solution to this.

**Comment by alonrbar** [comment] 2024-05-25 06:49
Duplicate of #54

**Closed by alonrbar** 2024-05-25 06:49 UTC
