### ISSUE TITLE
Replacing of tags in header and footer not working

### ISSUE THREAD

**Issue by rubenkaiser** [alonrbar/easy-template-x#43] opened 2021-02-18 14:26 UTC
I'm not having any success replacing tags in the header and footer of documents allthough it should be possible since version 0.12. Can someone provide a working example?

**Comment by alonrbar** [comment] 2021-02-18 14:42
Take a look here: https://github.com/alonrbar/easy-template-x/blob/17218d9c0509e3e71c88202a4cd1c4b018833695/test/fixtures/header.tests.ts#L10

It uses the template from here: https://github.com/alonrbar/easy-template-x/blob/master/test/fixtures/files/header%20and%20footer.docx

Let me know if it does not work for you.

**Comment by rubenkaiser** [comment] 2021-02-19 08:04
Found out that in a new document with a standard header and footer it does work. In my previous document however the header and footer are different with sections.

<img width="236" alt="Screenshot 2021-02-19 at 09 03 41" src="https://user-images.githubusercontent.com/3341102/108475800-7c875380-7291-11eb-81fc-8d5c989cd815.png">

For now I will use the default header and footer.

**Comment by rubenkaiser** [comment] 2021-02-19 14:38
Found out when this problem arises. I you add a page with a different orientation (landscape) Word will divide the document and it's headers in different sections. Keeping the orientation consistent, which is very likely for most use cases, is the solution for now.

**Comment by alonrbar** [comment] 2021-03-05 07:18
I'm closing this issue now. Not planning to implement support for different orientations at the moment. If this proves to be critical in the future feel free to re-open.

**Closed by alonrbar** 2021-03-05 07:18 UTC

**Comment by tadmi** [comment] 2023-07-13 10:32
The problem is also observed when there are several sections: tags are replaced only in the headers and footers of the last section
