### ISSUE TITLE
Browser Version

### ISSUE THREAD

**Issue by muthugp** [alonrbar/easy-template-x#57] opened 2021-07-22 06:22 UTC
Hi,
It looks like a very useful plugin. 
I  want to try this in a standard Javascript in browser, without typescript, import, export.
Your browser version is in Typescript.
Can you provide the standard JS to work in browser and code snippet?
Thanks,
Muthu

**Comment by alonrbar** [comment] 2021-07-22 08:24
Not sure I understand what you mean. This example is in JavaScript: https://github.com/alonrbar/easy-template-x#browser-example. 
If you are trying to run it as-is, you are right it won't work because async/await is not supported on top level code. You need to wrap the code with an async function, like this:

```javascript
async function main(){
  const response = ...
  ...
}
main()
```

Does that answer your question?

**Comment by muthugp** [comment] 2021-07-22 09:10
Thanks for the quick response.
Since i couldn't find the dist/compiled JS, i refer from here - https://www.jsdelivr.com/package/npm/easy-template-x
In my page, i have reference to "https://cdn.jsdelivr.net/npm/easy-template-x@2.0.0/dist/cjs/easy-template-x.min.js" and my js file with your browser-example snippet.
Since few other references are missing (not bundled) i get below error

![image](https://user-images.githubusercontent.com/11862964/126615237-1a4dd545-0a7c-49a6-a215-3cf2091c2e28.png)

Note: I use ES6 Javascript version (not typescript). If you could give me a link to refer your plugin (with all references) that would be really great.

Thank you.

**Comment by muthugp** [comment] 2021-07-22 21:57
Hi Alonrbar,
Sorry if i still confusing you. 
I am just wondering if there is compiled version (distributed file) that i can refer in my HTML form to work in browser.
Thanks.

**Comment by alonrbar** [comment] 2021-07-23 06:34
Hi, 

You cannot consume `easy-template-x` by referencing directly it in a script tag. You need to use a [JavaScript bundler](https://www.google.com/search?q=js+bundler) like [Webpack](https://webpack.js.org/) or [Parcel](https://parceljs.org/).

I also encourage you to checkout the [live demo](https://codesandbox.io/s/easy-template-x-demo-x4ppu) which demonstrates how to do what you want. You can follow the instructions I wrote [here](https://github.com/alonrbar/easy-template-x/issues/21#issuecomment-570793141) to run it locally (it relies on Parcel for bundling and running a dev server).

**Comment by alonrbar** [comment] 2021-07-23 06:34
Duplicate of: https://github.com/alonrbar/easy-template-x/issues/47

**Closed by alonrbar** 2021-07-23 06:34 UTC

**Comment by muthugp** [comment] 2021-07-23 08:31
Thanks Alonrbar.
